### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by evhumphrey** [SamArdrey/Anagram#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
    - [ ] each wiki page is listed in bullet points
    - [ ] all links route the correct page

## Comments

* Nice! Make sure to complete the MVP list as it will give you a schedule you will work with during fullstack.
---

# MVP List

- [ ] Should have 7 MVPs.
    - [ ] 3 of those are User Auth, Heroku, and Production README.
    - [ ] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [ ] Contains a description sentence of the app
  - [ ] Includes the following list for the 4 app specific MVPs:
    - [ ] Adequate styling
    - [ ] Smooth, bug-free navigation
    - [ ] Adequate and appropriate seeds to demonstrate the feature
- [ ] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each MVP
- [ ] Correctly formatted
    - [ ] MVPs are listed in an ordered list
    - [ ] Each MVP is broken down into bullet points

## Comments

* Make sure to add this to give yourself a timeline
---

# Database Schema

- [x] Contains correct datatypes
- [ ] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

* I don't think `image_id` for `comments` is needed; you'll likely grab the image from the user (author of comment)
* The pair of `[:followed_id, :followee_id]`, you should have unique true (so a user can't follow the same user more than once). 
* `followed_id` should not allow null entries
* For `post_likes`, make sure to add an index on `image_id`. adding an index on the pair `[:user_id, :image_id]` will add an index on `user_id`and the pair, but not `image_id. 

---

# Sample State

- [x] State shape is flat!
- [ ] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [ ] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

* Make sure to add three backticks instead of one to make it render correctly in markdown
---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments

* Remove any `GET ... new` or `GET ... edit` endpoint; react will take care of these now
---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments

**Comment by SamArdrey** [comment]
I think i got it all!
